# Generated by Django 2.2.6 on 2020-01-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='qs',
        ),
    ]
