# Generated by Django 2.2.6 on 2020-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_remove_session_qs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
